name: dino
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
- python=3.6.15
- pytorch=1.7.1
- torchvision=0.8.2
- cudatoolkit=11.0
- numpy=1.19.2
- scipy=1.5.2
- pillow=8.0.1
- tqdm=4.50.2
- pytorch-lightning=1.4.6
- torchmetrics=0.6.0
- efficientnet-pytorch=0.7.0
- fvcore=0.1.2.post20201122
- gym=0.17.2
- gym-box2d=0.17.2
- hydra-core=1.1.1
- ffmpeg=4.3.1
- h5py=2.10.0
- setuptools=49.6.0
- pip=21.0.1
- pip:
    - opencv-python==4.5.1.48
    - moviepy==1.0.3
    - stable-baselines3==0.8.0
    - importlib-resources==3.0.0
    - imgaug==0.4.0
    - notebook==6.4.4
    - scikit-video==1.1.11
    - wandb==0.10.12
    - gpustat==0.6.0
    - timm==0.3.2
    - ipywidgets==7.7.2